name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-web .

      - name: Test Docker image
        run: docker run -d --name test-container -p 8080:80 devops-web

      - name: Test application
        run: curl http://localhost:8080
